// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common_enum.proto

package com.jacey.game.common.proto3;

public final class CommonEnum {
  private CommonEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 服务器类型
   * </pre>
   *
   * Protobuf enum {@code com.jacey.game.common.proto3.RemoteServerTypeEnum}
   */
  public enum RemoteServerTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ServerTypeLogic = 0;</code>
     */
    ServerTypeLogic(0),
    /**
     * <code>ServerTypeBattle = 1;</code>
     */
    ServerTypeBattle(1),
    /**
     * <code>ServerTypeGateway = 2;</code>
     */
    ServerTypeGateway(2),
    /**
     * <code>ServerTypeGm = 3;</code>
     */
    ServerTypeGm(3),
    /**
     * <code>ServerTypeChat = 4;</code>
     */
    ServerTypeChat(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ServerTypeLogic = 0;</code>
     */
    public static final int ServerTypeLogic_VALUE = 0;
    /**
     * <code>ServerTypeBattle = 1;</code>
     */
    public static final int ServerTypeBattle_VALUE = 1;
    /**
     * <code>ServerTypeGateway = 2;</code>
     */
    public static final int ServerTypeGateway_VALUE = 2;
    /**
     * <code>ServerTypeGm = 3;</code>
     */
    public static final int ServerTypeGm_VALUE = 3;
    /**
     * <code>ServerTypeChat = 4;</code>
     */
    public static final int ServerTypeChat_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RemoteServerTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RemoteServerTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return ServerTypeLogic;
        case 1: return ServerTypeBattle;
        case 2: return ServerTypeGateway;
        case 3: return ServerTypeGm;
        case 4: return ServerTypeChat;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RemoteServerTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RemoteServerTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RemoteServerTypeEnum>() {
            public RemoteServerTypeEnum findValueByNumber(int number) {
              return RemoteServerTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jacey.game.common.proto3.CommonEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final RemoteServerTypeEnum[] VALUES = values();

    public static RemoteServerTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RemoteServerTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jacey.game.common.proto3.RemoteServerTypeEnum)
  }

  /**
   * <pre>
   * GM命令类型
   * </pre>
   *
   * Protobuf enum {@code com.jacey.game.common.proto3.GmCmdTypeEnum}
   */
  public enum GmCmdTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * GM命令 重新加载配置表格
     * </pre>
     *
     * <code>GmCmdReloadTableConfig = 0;</code>
     */
    GmCmdReloadTableConfig(0),
    /**
     * <pre>
     * GM命令 关服
     * </pre>
     *
     * <code>GmCmdCloseServer = 1;</code>
     */
    GmCmdCloseServer(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * GM命令 重新加载配置表格
     * </pre>
     *
     * <code>GmCmdReloadTableConfig = 0;</code>
     */
    public static final int GmCmdReloadTableConfig_VALUE = 0;
    /**
     * <pre>
     * GM命令 关服
     * </pre>
     *
     * <code>GmCmdCloseServer = 1;</code>
     */
    public static final int GmCmdCloseServer_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GmCmdTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GmCmdTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return GmCmdReloadTableConfig;
        case 1: return GmCmdCloseServer;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GmCmdTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GmCmdTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GmCmdTypeEnum>() {
            public GmCmdTypeEnum findValueByNumber(int number) {
              return GmCmdTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jacey.game.common.proto3.CommonEnum.getDescriptor().getEnumTypes().get(1);
    }

    private static final GmCmdTypeEnum[] VALUES = values();

    public static GmCmdTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GmCmdTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jacey.game.common.proto3.GmCmdTypeEnum)
  }

  /**
   * <pre>
   * 玩家在线状态
   * </pre>
   *
   * Protobuf enum {@code com.jacey.game.common.proto3.UserOnlineStateEnum}
   */
  public enum UserOnlineStateEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Offline = 0;</code>
     */
    Offline(0),
    /**
     * <code>Online = 1;</code>
     */
    Online(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Offline = 0;</code>
     */
    public static final int Offline_VALUE = 0;
    /**
     * <code>Online = 1;</code>
     */
    public static final int Online_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserOnlineStateEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UserOnlineStateEnum forNumber(int value) {
      switch (value) {
        case 0: return Offline;
        case 1: return Online;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserOnlineStateEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserOnlineStateEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserOnlineStateEnum>() {
            public UserOnlineStateEnum findValueByNumber(int number) {
              return UserOnlineStateEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jacey.game.common.proto3.CommonEnum.getDescriptor().getEnumTypes().get(2);
    }

    private static final UserOnlineStateEnum[] VALUES = values();

    public static UserOnlineStateEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserOnlineStateEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jacey.game.common.proto3.UserOnlineStateEnum)
  }

  /**
   * <pre>
   * 玩家行为状态
   * </pre>
   *
   * Protobuf enum {@code com.jacey.game.common.proto3.UserActionStateEnum}
   */
  public enum UserActionStateEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ActionNone = 0;</code>
     */
    ActionNone(0),
    /**
     * <pre>
     * 匹配中
     * </pre>
     *
     * <code>Matching = 1;</code>
     */
    Matching(1),
    /**
     * <pre>
     * 对战中
     * </pre>
     *
     * <code>Playing = 2;</code>
     */
    Playing(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ActionNone = 0;</code>
     */
    public static final int ActionNone_VALUE = 0;
    /**
     * <pre>
     * 匹配中
     * </pre>
     *
     * <code>Matching = 1;</code>
     */
    public static final int Matching_VALUE = 1;
    /**
     * <pre>
     * 对战中
     * </pre>
     *
     * <code>Playing = 2;</code>
     */
    public static final int Playing_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserActionStateEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UserActionStateEnum forNumber(int value) {
      switch (value) {
        case 0: return ActionNone;
        case 1: return Matching;
        case 2: return Playing;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserActionStateEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserActionStateEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserActionStateEnum>() {
            public UserActionStateEnum findValueByNumber(int number) {
              return UserActionStateEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jacey.game.common.proto3.CommonEnum.getDescriptor().getEnumTypes().get(3);
    }

    private static final UserActionStateEnum[] VALUES = values();

    public static UserActionStateEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserActionStateEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jacey.game.common.proto3.UserActionStateEnum)
  }

  /**
   * <pre>
   * 对战类型
   * </pre>
   *
   * Protobuf enum {@code com.jacey.game.common.proto3.BattleTypeEnum}
   */
  public enum BattleTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NoneType = 0;</code>
     */
    NoneType(0),
    /**
     * <pre>
     * 1V1
     * </pre>
     *
     * <code>BattleTypeTwoPlayer = 1;</code>
     */
    BattleTypeTwoPlayer(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NoneType = 0;</code>
     */
    public static final int NoneType_VALUE = 0;
    /**
     * <pre>
     * 1V1
     * </pre>
     *
     * <code>BattleTypeTwoPlayer = 1;</code>
     */
    public static final int BattleTypeTwoPlayer_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BattleTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BattleTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return NoneType;
        case 1: return BattleTypeTwoPlayer;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BattleTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BattleTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BattleTypeEnum>() {
            public BattleTypeEnum findValueByNumber(int number) {
              return BattleTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jacey.game.common.proto3.CommonEnum.getDescriptor().getEnumTypes().get(4);
    }

    private static final BattleTypeEnum[] VALUES = values();

    public static BattleTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BattleTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jacey.game.common.proto3.BattleTypeEnum)
  }

  /**
   * <pre>
   * 玩家被封禁原因
   * </pre>
   *
   * Protobuf enum {@code com.jacey.game.common.proto3.UserForbidReasonEnum}
   */
  public enum UserForbidReasonEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * GM管理员手工操作封禁
     * </pre>
     *
     * <code>UserForbidReasonGmOperate = 0;</code>
     */
    UserForbidReasonGmOperate(0),
    /**
     * <pre>
     * 服务器发现明显只能是玩家破解、伪造数据包进行请求时，自动封禁
     * </pre>
     *
     * <code>UserForbidReasonCheat = 1;</code>
     */
    UserForbidReasonCheat(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * GM管理员手工操作封禁
     * </pre>
     *
     * <code>UserForbidReasonGmOperate = 0;</code>
     */
    public static final int UserForbidReasonGmOperate_VALUE = 0;
    /**
     * <pre>
     * 服务器发现明显只能是玩家破解、伪造数据包进行请求时，自动封禁
     * </pre>
     *
     * <code>UserForbidReasonCheat = 1;</code>
     */
    public static final int UserForbidReasonCheat_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserForbidReasonEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UserForbidReasonEnum forNumber(int value) {
      switch (value) {
        case 0: return UserForbidReasonGmOperate;
        case 1: return UserForbidReasonCheat;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserForbidReasonEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserForbidReasonEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserForbidReasonEnum>() {
            public UserForbidReasonEnum findValueByNumber(int number) {
              return UserForbidReasonEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jacey.game.common.proto3.CommonEnum.getDescriptor().getEnumTypes().get(5);
    }

    private static final UserForbidReasonEnum[] VALUES = values();

    public static UserForbidReasonEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserForbidReasonEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jacey.game.common.proto3.UserForbidReasonEnum)
  }

  /**
   * <pre>
   * 被强制下线的原因
   * </pre>
   *
   * Protobuf enum {@code com.jacey.game.common.proto3.ForceOfflineReasonEnum}
   */
  public enum ForceOfflineReasonEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 服务器不可用
     * </pre>
     *
     * <code>ForceOfflineServerNotAvailable = 0;</code>
     */
    ForceOfflineServerNotAvailable(0),
    /**
     * <pre>
     * 同一账号同时异地登录，踢掉之前登录的
     * </pre>
     *
     * <code>ForceOfflineSameUserLogin = 1;</code>
     */
    ForceOfflineSameUserLogin(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 服务器不可用
     * </pre>
     *
     * <code>ForceOfflineServerNotAvailable = 0;</code>
     */
    public static final int ForceOfflineServerNotAvailable_VALUE = 0;
    /**
     * <pre>
     * 同一账号同时异地登录，踢掉之前登录的
     * </pre>
     *
     * <code>ForceOfflineSameUserLogin = 1;</code>
     */
    public static final int ForceOfflineSameUserLogin_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ForceOfflineReasonEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ForceOfflineReasonEnum forNumber(int value) {
      switch (value) {
        case 0: return ForceOfflineServerNotAvailable;
        case 1: return ForceOfflineSameUserLogin;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ForceOfflineReasonEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ForceOfflineReasonEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ForceOfflineReasonEnum>() {
            public ForceOfflineReasonEnum findValueByNumber(int number) {
              return ForceOfflineReasonEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jacey.game.common.proto3.CommonEnum.getDescriptor().getEnumTypes().get(6);
    }

    private static final ForceOfflineReasonEnum[] VALUES = values();

    public static ForceOfflineReasonEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ForceOfflineReasonEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jacey.game.common.proto3.ForceOfflineReasonEnum)
  }

  /**
   * <pre>
   * 聊天室类型
   * </pre>
   *
   * Protobuf enum {@code com.jacey.game.common.proto3.ChatRoomTypeEnum}
   */
  public enum ChatRoomTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 1v1对战聊天室
     * </pre>
     *
     * <code>TwoPlayerBattleChatRoomType = 0;</code>
     */
    TwoPlayerBattleChatRoomType(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 1v1对战聊天室
     * </pre>
     *
     * <code>TwoPlayerBattleChatRoomType = 0;</code>
     */
    public static final int TwoPlayerBattleChatRoomType_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ChatRoomTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ChatRoomTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return TwoPlayerBattleChatRoomType;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChatRoomTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChatRoomTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChatRoomTypeEnum>() {
            public ChatRoomTypeEnum findValueByNumber(int number) {
              return ChatRoomTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jacey.game.common.proto3.CommonEnum.getDescriptor().getEnumTypes().get(7);
    }

    private static final ChatRoomTypeEnum[] VALUES = values();

    public static ChatRoomTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChatRoomTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jacey.game.common.proto3.ChatRoomTypeEnum)
  }

  /**
   * <pre>
   * 对战聊天文本作用域
   * </pre>
   *
   * Protobuf enum {@code com.jacey.game.common.proto3.BattleChatTextScopeEnum}
   */
  public enum BattleChatTextScopeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 队友
     * </pre>
     *
     * <code>TeammateScope = 0;</code>
     */
    TeammateScope(0),
    /**
     * <pre>
     * 所有人（战局中的所有人。包括对手、队友）
     * </pre>
     *
     * <code>EveryoneScope = 1;</code>
     */
    EveryoneScope(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 队友
     * </pre>
     *
     * <code>TeammateScope = 0;</code>
     */
    public static final int TeammateScope_VALUE = 0;
    /**
     * <pre>
     * 所有人（战局中的所有人。包括对手、队友）
     * </pre>
     *
     * <code>EveryoneScope = 1;</code>
     */
    public static final int EveryoneScope_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BattleChatTextScopeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BattleChatTextScopeEnum forNumber(int value) {
      switch (value) {
        case 0: return TeammateScope;
        case 1: return EveryoneScope;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BattleChatTextScopeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BattleChatTextScopeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BattleChatTextScopeEnum>() {
            public BattleChatTextScopeEnum findValueByNumber(int number) {
              return BattleChatTextScopeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jacey.game.common.proto3.CommonEnum.getDescriptor().getEnumTypes().get(8);
    }

    private static final BattleChatTextScopeEnum[] VALUES = values();

    public static BattleChatTextScopeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BattleChatTextScopeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jacey.game.common.proto3.BattleChatTextScopeEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021common_enum.proto\022\034com.jacey.game.comm" +
      "on.proto3*~\n\024RemoteServerTypeEnum\022\023\n\017Ser" +
      "verTypeLogic\020\000\022\024\n\020ServerTypeBattle\020\001\022\025\n\021" +
      "ServerTypeGateway\020\002\022\020\n\014ServerTypeGm\020\003\022\022\n" +
      "\016ServerTypeChat\020\004*A\n\rGmCmdTypeEnum\022\032\n\026Gm" +
      "CmdReloadTableConfig\020\000\022\024\n\020GmCmdCloseServ" +
      "er\020\001*.\n\023UserOnlineStateEnum\022\013\n\007Offline\020\000" +
      "\022\n\n\006Online\020\001*@\n\023UserActionStateEnum\022\016\n\nA" +
      "ctionNone\020\000\022\014\n\010Matching\020\001\022\013\n\007Playing\020\002*7" +
      "\n\016BattleTypeEnum\022\014\n\010NoneType\020\000\022\027\n\023Battle" +
      "TypeTwoPlayer\020\001*P\n\024UserForbidReasonEnum\022" +
      "\035\n\031UserForbidReasonGmOperate\020\000\022\031\n\025UserFo" +
      "rbidReasonCheat\020\001*[\n\026ForceOfflineReasonE" +
      "num\022\"\n\036ForceOfflineServerNotAvailable\020\000\022" +
      "\035\n\031ForceOfflineSameUserLogin\020\001*3\n\020ChatRo" +
      "omTypeEnum\022\037\n\033TwoPlayerBattleChatRoomTyp" +
      "e\020\000*?\n\027BattleChatTextScopeEnum\022\021\n\rTeamma" +
      "teScope\020\000\022\021\n\rEveryoneScope\020\001B\002H\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
