// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: local_server.proto

package com.jacey.game.common.proto3;

public final class LocalServer {
  private LocalServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 服务器内部通信协议名
   * </pre>
   *
   * Protobuf enum {@code com.jacey.game.common.proto3.LocalRpcNameEnum}
   */
  public enum LocalRpcNameEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 由于proto3中enum首位必须是0所以设置该标识字段
     * </pre>
     *
     * <code>None = 0;</code>
     */
    None(0),
    /**
     * <pre>
     * 向GM服务器注册
     * </pre>
     *
     * <code>LocalRpcRegistToGmServer = 300001;</code>
     */
    LocalRpcRegistToGmServer(300001),
    /**
     * <pre>
     * logicServer循环通知自己进行匹配计算
     * </pre>
     *
     * <code>LocalRpcLogicServerMatch = 310001;</code>
     */
    LocalRpcLogicServerMatch(310001),
    /**
     * <pre>
     * battleServer通知初始化战斗
     * </pre>
     *
     * <code>LocalRpcBattleServerInitBattle = 320001;</code>
     */
    LocalRpcBattleServerInitBattle(320001),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 由于proto3中enum首位必须是0所以设置该标识字段
     * </pre>
     *
     * <code>None = 0;</code>
     */
    public static final int None_VALUE = 0;
    /**
     * <pre>
     * 向GM服务器注册
     * </pre>
     *
     * <code>LocalRpcRegistToGmServer = 300001;</code>
     */
    public static final int LocalRpcRegistToGmServer_VALUE = 300001;
    /**
     * <pre>
     * logicServer循环通知自己进行匹配计算
     * </pre>
     *
     * <code>LocalRpcLogicServerMatch = 310001;</code>
     */
    public static final int LocalRpcLogicServerMatch_VALUE = 310001;
    /**
     * <pre>
     * battleServer通知初始化战斗
     * </pre>
     *
     * <code>LocalRpcBattleServerInitBattle = 320001;</code>
     */
    public static final int LocalRpcBattleServerInitBattle_VALUE = 320001;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LocalRpcNameEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LocalRpcNameEnum forNumber(int value) {
      switch (value) {
        case 0: return None;
        case 300001: return LocalRpcRegistToGmServer;
        case 310001: return LocalRpcLogicServerMatch;
        case 320001: return LocalRpcBattleServerInitBattle;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LocalRpcNameEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LocalRpcNameEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LocalRpcNameEnum>() {
            public LocalRpcNameEnum findValueByNumber(int number) {
              return LocalRpcNameEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jacey.game.common.proto3.LocalServer.getDescriptor().getEnumTypes().get(0);
    }

    private static final LocalRpcNameEnum[] VALUES = values();

    public static LocalRpcNameEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LocalRpcNameEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jacey.game.common.proto3.LocalRpcNameEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022local_server.proto\022\034com.jacey.game.com" +
      "mon.proto3*\202\001\n\020LocalRpcNameEnum\022\010\n\004None\020" +
      "\000\022\036\n\030LocalRpcRegistToGmServer\020\341\247\022\022\036\n\030Loc" +
      "alRpcLogicServerMatch\020\361\365\022\022$\n\036LocalRpcBat" +
      "tleServerInitBattle\020\201\304\023B\002H\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
